apiVersion: v1
kind: Pod
metadata:
  name: pod-with-node-selector
spec:
  containers:
    - image: nginx:1.12
      name: nginx
      ports:
        - containerPort: 80
  nodeSelector:
    nodeSelectorKey: nodeSelectorValue