apiVersion: v1
kind: Pod
metadata:
  name: pod-with-required-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: affinityKey
                operator: In
                values:
                  - affinityValue
  containers:
    - image: nginx:1.12
      name: nginx
      ports:
        - containerPort: 80
