---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-infinite
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 60
  template:
    spec:
      containers:
        - name: job
          image: busybox
          args:
            - /bin/sh
            - -c
            - while true; do date; echo 'Hello World!'; done;
      restartPolicy: Never
...