---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-success
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 60
  template:
    spec:
      containers:
        - name: job
          image: busybox
          args:
            - /bin/sh
            - -c
            - date; echo 'Hello World!'
      restartPolicy: Never
...