apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-node-exporter
  labels:
    k8s-app: monitoring
spec:
  selector:
    matchLabels:
      name: prometheus-node-exporter
  template:
    metadata:
      labels:
        name: prometheus-node-exporter
    spec:
      tolerations:
        - key: testTaintKeyOnControlPlane
          operator: Exists
          effect: NoSchedule
        - key: testTaintKeyOnWorker1
          operator: Exists
          effect: NoSchedule
      containers:
        - name: prometheus-node-exporter
          image: prom/node-exporter:v1.7.0
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
      # it may be desirable to set a high priority class to ensure that a DaemonSet Pod
      # preempts running Pods
      # priorityClassName: important
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
